### ISSUE TITLE
Hindi language support for the app

### ISSUE THREAD

**Issue by mohitsoni-dev** [ZorinOS/zorin-connect-android#12]
I would like to add support for Hindi language to this application. Please assign me this issue I would be grateful to contribute.

**Comment by ArtyomZorin** [comment]
Thanks for your kind offer to contribute!

As the Zorin Connect Android app is based on KDE Connect, we would recommend you to contribute translations to the upstream project, so that both apps can benefit from your Hindi translations.

You can learn more about how to contribute translations to the upstream kdeconnect-android project in the "Contributing" section of this page: https://github.com/KDE/kdeconnect-android#contributing
