### ISSUE TITLE
[Feature Request] Touchpad option

### ISSUE THREAD

**Issue by Mhowser** [ZorinOS/zorin-connect-android#3]
Turns your phone into a wireless touchpad for the desktop. It would be a great thing to have as a feature!

**Comment by ArtyomZorin** [comment]
This feature already exists in the app. If you've connected your phone to your computer with Zorin Connect, you can open the Android app and select the "Remote input" option to use your phone's screen as a touchpad and keyboard.

**Comment by Mhowser** [comment]
I do not have the remote input option. I have the latest version from
Google play.

**Comment by ArtyomZorin** [comment]
It appears that you may have selected to use the Wayland display server, which is currently experimental does not fully support the remote features of Zorin Connect yet. In order to switch back to the standard (X.org) display server which may fix the issue for you, please follow these steps:
At the login screen, please select your username.
Click on the gear icon beside the sign in button to open the desktop environment menu.
Select the "Zorin Desktop" option, not the option ending with "on Wayland".
You should now be able to log in normally

**Comment by Mhowser** [comment]
That was it! Thanks for your help! Do you think it would be a good idea to
let users know that some features won't work with Wayland yet in the app?

**Comment by nicolasmaia** [comment]
@Mhowser I think a disclaimer like that would be useful
