### ISSUE TITLE
Duplicated notifications

### ISSUE THREAD

**Issue by nicolasmaia** [ZorinOS/zorin-connect-android#7]
I'm not sure this is fixable, but sometimes we get duplicated notifications, for example, from Tutanota (desktop verson) and Tutanota app (mobile).

Is there a way to avoid this?

**Comment by ArtyomZorin** [comment]
In order to disable syncing notifications for certain apps from your phone to your computer (if you already receive the same notifications from the desktop apps on your computer), please follow these steps:
Open the Zorin Connect app on your phone
Select your computer from the Devices menu
Tap the 3 dot menu button (in the top-right corner) and open "Plugin settings"
Press the gear button beside the "Notification sync" option
Uncheck the apps which you don't wish to sync notifications from your phone on (such as Tutanot in your case)
