### ISSUE TITLE
Translations

### ISSUE THREAD

**Issue by nicolasmaia** [ZorinOS/zorin-connect-android#8]
I see that gsconnect is managing translations through Crowdin, which are updated regularly.

Is this extension using a third party service for translations, too? I'd like to contribute but I want to make sure first.

**Comment by ArtyomZorin** [comment]
The Zorin Connect Android app receives translations from the KDE Connect Android app (on which it is based). We would recommend contributing translations to the upstream project (kdeconnect-android) as part of your language team on the KDE Localization website so that they benefit both projects: https://l10n.kde.org/

**Comment by nicolasmaia** [comment]
Thanks! Will do.
